dist: xenial
language: python

python:
  - 3.8
  - 3.7
  - 3.6

env:
  matrix:
  - DJANGO='django21' CMS='cms36'
  - TOXENV='pep8'
  - DJANGO='django22' CMS='cms37'
  - DJANGO='django22' CMS='cms37'

install:
  - pip install -U tox>=1.8 coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PYVER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO-$CMS; fi"

script: COMMAND='coverage run' tox -e$TOXENV

before_install:
  - pip install codecov
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 3.6
    env: TOXENV='pep8'
  include:
  - stage: deploy
    python: 3.8
    install: skip
    script: 
      - python setup.py sdist
    deploy:
      provider: pypi
      user: "__token__"
      skip_upload_docs: true
      skip_cleanup: true
      distributions: "sdist"
      password:
        secure: REpOJvkIBQZbHV5exgqtoZ41QsU1Fm/20HplfmmTi+WITUjO2Dxbdxt49EcG0CCgHu28zakPHiAkmWzqLuu5YupfyzVVfupKNOxLcbsPYVYV9LRfqEUv3EiMSkfbFq1hDJppZJV21bnLOILHMjZKgr0XLOpaPpIAeOu5HsxNg7cFiRQTbkjFLe7Q/cOvaqxV9KUJfiSh6uylbFAdnlvz2w1xV7RN0ln5syspfIRLCv4cvipOX/bJ5xujcBGjqfZ4QB7WI/ZZxXZuA0s8myGYqXHMGCMbS62X4meu5SbhhRV1EpN9V9i9VUDVU+/2d6Z0mpvGEIwYKDbUqclpqU5HMgjOV43eCeAqgQxXi9PaIIEoIHIDQWdUA3SqmFb77HsX99GN8fWfEM6Zj645IaiQvMfV1V3Hr5uV5FYYg1kgFWgE6kgi07Dv6EawgXf2yQN/Y5NKHmDLfXg/eUqkFVDrAUFNWWa0GQ7wMtSHF3TpVVlAQOtvvSh9ARBQEQFVMPybNCVavPcO1ndQ+EiYPuAXSvbNDYaeIRzxeL9iCqKjGRQAZCN9RxLUQaVGu6ieb4LJsU/U/Y6sT7XYBQ05nnilonUnzHTEBv1NexrtjNi7dwI1STQjy0QwbCkjPbU3Ku1vJ09Z3qVUQNk3BvP7jzoX/onaTZxO48vQ0Oj9y2bxwqY=
      server: https://test.pypi.org/legacy/

# deploy:
#   script: 
#     make build
#     python setup.py publish
#   provider: script
#   on:
#     branch: master