language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

env:
  matrix:
  - TOXENV='pep8'
  - DJANGO='django22' CMS='cms37'
  - DJANGO='django22' CMS='cms37'
  - DJANGO='django21' CMS='cms36'
  - DJANGO='django111' CMS='cms37'
  - DJANGO='django111' CMS='cms36'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox>=1.8 coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PYVER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO-$CMS; fi"

# command to run tests, e.g. python setup.py test
script: 
  COMMAND='coverage run' tox -e$TOXENV

before_install:
  - pip install codecov
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.6
    env: TOXENV='pep8'

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "srI1VOeOoF2Z1WaZnrAfEBBAbzJYs40HmqWpRHGuwk4L5xNxU+bBgaLw1ASc6Bp+rKvAR52wLdHszIXZaNTe/nNKiiMFpGpxBWaI1JNb/s+grBPUjQAtg6gyUyg09cV+t7kILBqHOInMCyIpil5FkUvbd9Wmf1vgq7PK+XSR3LkALm3U0syBn6VSULIfgsck5I6ItUKpR82qzUAOg0Ak/d4Pp9jkKUJ0GVotMRNgUUJVD9QCBP4x0dNqsiTBlUVe/doD5LPkgSO6jjaZR0VfyhUAkK+0lyk3/M8kShn/GkvlUQ0Th+Feo79gcUbz4CwXUTM+PaWgSQTD8+/QAGZ+m7gM2Edgim0uhkibGBjw63ddP99/oW826SJaVYdp52Ab8iVVH2Yo3D6iQpblBsoM7nLgKwaRscrga3+HNLW1hQOD6nZPzPSzH8jrshWV4kpR+s1NNcHc2kqUhMHpGATS4KvaqCbUfca/y4J/DmzY/RQ5DhZ4SBwG8XdwurQ4XVd7nZREg298kenwlt/nCsKzatNHVfNWtK2UOCtyYi59yYSjjFxLLX0rH9UgGQl6xH/r2k322/4FUDOngdBCrrnVHJZP3wnJkx+Pb7mhkp4HjLVcoQzOM03WwGNEykV93X/o5en4eNooGbjr7HhpfJXhsT0T/4LoJT097GDP+pUMSlg="
  on:
    tags: true
  server: https://test.pypi.org/

# deploy:
#   script: 
#     make build
#     python setup.py publish
#   provider: script
#   on:
#     branch: master